### ISSUE TITLE
Yarn test blows up

### ISSUE THREAD

**Issue by bonomat** [comit-network/waves#111]
When running `yarn test` a giant error message is shown. This does not effect the test though: 

See `waves_test` here for example: https://github.com/comit-network/droplet/pull/110/checks?check_run_id=1660725116 

```bash
  ● Console

    console.error
      Warning: An update to ConfirmSwapDrawer inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at reactjs.org/link/wrap-tests-with-act
          at ConfirmSwapDrawer (/home/runner/work/droplet/droplet/waves/src/ConfirmSwapDrawer.tsx:34:45)
          at div
          at App (/home/runner/work/droplet/droplet/waves/src/App.tsx:172:21)
          at Router (/home/runner/work/droplet/droplet/waves/node_modules/react-router/cjs/react-router.js:99:30)
          at BrowserRouter (/home/runner/work/droplet/droplet/waves/node_modules/react-router-dom/cjs/react-router-dom.js:67:35)
          at SSEProvider (/home/runner/work/droplet/droplet/waves/node_modules/react-hooks-sse/dist/cjs/SSEContext.js:34:23)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at node_modules/swr/dist/index.js:1:7507
      at node_modules/swr/dist/index.js:1:9245
      at step (node_modules/swr/dist/index.js:1:3918)
      at Object.throw (node_modules/swr/dist/index.js:1:3203)

    console.error
      Warning: An update to App inside a test was not wrapped in act(...).
      
      When testing, code that causes React state updates should be wrapped into act(...):
      
      act(() => {
        /* fire events that update state */
      });
      /* assert on the output */
      
      This ensures that you're testing the behavior the user would see in the browser. Learn more at reactjs.org/link/wrap-tests-with-act
          at App (/home/runner/work/droplet/droplet/waves/src/App.tsx:172:21)
          at Router (/home/runner/work/droplet/droplet/waves/node_modules/react-router/cjs/react-router.js:99:30)
          at BrowserRouter (/home/runner/work/droplet/droplet/waves/node_modules/react-router-dom/cjs/react-router-dom.js:67:35)
          at SSEProvider (/home/runner/work/droplet/droplet/waves/node_modules/react-hooks-sse/dist/cjs/SSEContext.js:34:23)

      at printWarning (node_modules/react-dom/cjs/react-dom.development.js:67:30)
      at error (node_modules/react-dom/cjs/react-dom.development.js:43:5)
      at warnIfNotCurrentlyActingUpdatesInDEV (node_modules/react-dom/cjs/react-dom.development.js:24064:9)
      at dispatchAction (node_modules/react-dom/cjs/react-dom.development.js:16135:9)
      at node_modules/swr/dist/index.js:1:7507
      at node_modules/swr/dist/index.js:1:9245
      at step (node_modules/swr/dist/index.js:1:3918)
      at Object.throw (node_modules/swr/dist/index.js:1:3203)

PASS src/RateService.test.tsx
```

**Comment by thomaseizinger** [comment]
Confirming that this is still an issue: https://github.com/comit-network/waves/runs/1803626396#step:6:219

**Comment by bonomat** [comment]
Seems to be fixed.
